baseURL = "https://reinnatalia25.github.io/casalimpia/"
languageCode = "en-us"
title = "Casa Limpia"

disableKinds = ["taxonomy","term"]

[params]
description = "Professional Exterior House Cleaning"
